# Generated by Django 5.0.14 on 2026-04-17 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('GENERAL', 'General Medicine'), ('CARDIOLOGY', 'Cardiology'), ('ORTHOPEDICS', 'Orthopedics'), ('PEDIATRICS', 'Pediatrics'), ('DERMATOLOGY', 'Dermatology'), ('ENT', 'ENT'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('NEUROLOGY', 'Neurology')], default='GENERAL', max_length=20)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('slot_time', models.DateTimeField(auto_now_add=True)),
                ('estimated_wait_time', models.PositiveIntegerField(default=15)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_slots', to='patients.patient')),
            ],
            options={
                'db_table': 'queue_slots',
                'ordering': ['priority', 'slot_time'],
            },
        ),
    ]
