# Generated by Codex on 2026-04-28

from datetime import time, timedelta

from django.db import migrations, models
from django.utils import timezone


QUEUE_DAY_START = time(4, 0)


def get_token_date(slot_time):
    local_time = timezone.localtime(slot_time)
    token_date = local_time.date()
    if local_time.time() < QUEUE_DAY_START:
        token_date -= timedelta(days=1)
    return token_date


def assign_existing_tokens(apps, schema_editor):
    QueueSlot = apps.get_model('queues', 'QueueSlot')
    counters = {}

    for slot in QueueSlot.objects.order_by('slot_time', 'id'):
        token_date = get_token_date(slot.slot_time)
        next_token = counters.get(token_date, 0) + 1
        counters[token_date] = next_token

        slot.token_date = token_date
        slot.token_number = next_token
        slot.save(update_fields=['token_date', 'token_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueslot',
            name='token_date',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='queueslot',
            name='token_number',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.RunPython(assign_existing_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='queueslot',
            name='token_date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='queueslot',
            name='token_number',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AddConstraint(
            model_name='queueslot',
            constraint=models.UniqueConstraint(
                fields=('token_date', 'token_number'),
                name='unique_daily_queue_token',
            ),
        ),
    ]
