# Generated by Codex on 2026-04-28

from django.db import migrations, models


def reassign_department_tokens(apps, schema_editor):
    QueueSlot = apps.get_model('queues', 'QueueSlot')
    counters = {}

    for slot in QueueSlot.objects.order_by('token_date', 'department', 'slot_time', 'id'):
        counter_key = (slot.token_date, slot.department)
        next_token = counters.get(counter_key, 0) + 1
        counters[counter_key] = next_token

        slot.token_number = next_token
        slot.save(update_fields=['token_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_daily_queue_tokens'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='queueslot',
            name='unique_daily_queue_token',
        ),
        migrations.RunPython(reassign_department_tokens, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='queueslot',
            constraint=models.UniqueConstraint(
                fields=('token_date', 'department', 'token_number'),
                name='unique_daily_department_queue_token',
            ),
        ),
    ]
