# Generated by Django 5.0.14 on 2026-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_department_queue_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueslot',
            name='actual_wait_time_mins',
            field=models.IntegerField(blank=True, help_text='Actual wait time recorded', null=True),
        ),
        migrations.AddField(
            model_name='queueslot',
            name='predicted_wait_time',
            field=models.PositiveIntegerField(blank=True, help_text='Wait time predicted by ML model', null=True),
        ),
        migrations.AddField(
            model_name='queueslot',
            name='prediction_error_mins',
            field=models.IntegerField(blank=True, help_text='Actual minus Predicted', null=True),
        ),
    ]
