# Generated by Codex on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='department',
            field=models.CharField(
                blank=True,
                choices=[
                    ('GENERAL', 'General Medicine'),
                    ('CARDIOLOGY', 'Cardiology'),
                    ('ORTHOPEDICS', 'Orthopedics'),
                    ('PEDIATRICS', 'Pediatrics'),
                    ('DERMATOLOGY', 'Dermatology'),
                    ('ENT', 'ENT'),
                    ('OPHTHALMOLOGY', 'Ophthalmology'),
                    ('NEUROLOGY', 'Neurology'),
                ],
                max_length=20,
            ),
        ),
    ]
