# Generated by Django 5.0.14 on 2026-04-28 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorprofile_department_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('GENERAL', 'General Medicine'), ('CARDIOLOGY', 'Cardiology'), ('ORTHOPEDICS', 'Orthopedics'), ('PEDIATRICS', 'Pediatrics'), ('DERMATOLOGY', 'Dermatology'), ('ENT', 'ENT'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('NEUROLOGY', 'Neurology')], help_text='Leave blank for central lab access to all departments.', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_profiles',
            },
        ),
    ]
