# Generated by Codex on 2026-04-28

from django.db import migrations


def create_existing_lab_profiles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    LabProfile = apps.get_model('accounts', 'LabProfile')

    for user in User.objects.filter(role='LAB'):
        LabProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_labprofile'),
    ]

    operations = [
        migrations.RunPython(create_existing_lab_profiles, migrations.RunPython.noop),
    ]
