# Generated by Django 5.0.14 on 2026-04-28 10:36

from django.db import migrations, models


def clear_old_doctor_department_values(apps, schema_editor):
    LabProfile = apps.get_model('accounts', 'LabProfile')
    valid_departments = {'BLOOD', 'URINE', 'XRAY', 'CT', 'MRI', 'ECG', 'USG', 'OTHER', ''}
    LabProfile.objects.exclude(department__in=valid_departments).update(department='')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_create_existing_lab_profiles'),
    ]

    operations = [
        migrations.RunPython(clear_old_doctor_department_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='labprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('BLOOD', 'Blood Test'), ('URINE', 'Urine Test'), ('XRAY', 'X-Ray'), ('CT', 'CT Scan'), ('MRI', 'MRI'), ('ECG', 'ECG'), ('USG', 'Ultrasound'), ('OTHER', 'Other Lab Tests')], help_text='Leave blank for central lab access to all lab test types.', max_length=20),
        ),
    ]
