# Generated by Django 5.0.14 on 2026-05-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_blood_group_patient_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
